# Writes web/supabase-runtime-config.js from repo-root .env (SUPABASE_URL + SUPABASE_ANON_KEY only).
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$dotEnvFile = Join-Path $root '.env'
$outPath = Join-Path $root 'web\supabase-runtime-config.local.js'

if (-not (Test-Path $dotEnvFile)) {
  Write-Error ".env not found at $dotEnvFile (copy .env.example or create .env)."
}

$url = ''
$anon = ''
Get-Content $dotEnvFile | ForEach-Object {
  $line = $_.Trim()
  if ($line -match '^\s*#' -or $line -eq '') { return }
  if ($line -match '^SUPABASE_URL=(.+)$') { $url = $Matches[1].Trim() }
  elseif ($line -match '^SUPABASE_ANON_KEY=(.+)$') { $anon = $Matches[1].Trim() }
}

if ($url -eq '' -or $anon -eq '') {
  Write-Error ".env must define SUPABASE_URL and SUPABASE_ANON_KEY."
}

$urlJs = ConvertTo-Json $url
$anonJs = ConvertTo-Json $anon

$content = @"
// Generated by scripts/sync_web_supabase_config.ps1 (gitignored). Do not commit.
window.factoryosSupabase = {
  url: $urlJs,
  anonKey: $anonJs,
};
"@

Set-Content -Path $outPath -Value $content -Encoding utf8
Write-Host "Wrote $outPath"
